export const PAGE_META = {
  introduction: { title: "Introduction", desc: "What Monoset is, what ships in the box, and when to reach for it." },
  installation: { title: "Installation", desc: "Install Monoset via the CSS tokens or the React component kit." },
  usage:        { title: "Basic usage", desc: "An end-to-end example with Monoset tokens and primitives." },
  colors:       { title: "Colors", desc: "The 12-step neutral ramp and the semantic tokens built on top of it." },
  typography:   { title: "Typography", desc: "Inter for UI, JetBrains Mono for code, a modular scale from 11px to 64px." },
  spacing:      { title: "Spacing & radii", desc: "A 4px base grid with named spacing and radius tokens." },
  motion:       { title: "Motion", desc: "Three durations, one easing curve. Monoset's approach to UI motion." },
  framer:       { title: "Framer Motion", desc: "JS-driven animation presets that match the CSS motion tokens." },
  buttons:      { title: "Button", desc: "Four variants, three sizes, four states. A React Button component." },
  inputs:       { title: "Input", desc: "Text fields, textareas, and selects with a Field wrapper." },
  badges:       { title: "Badge", desc: "Small labels for status, counts, and category tags." },
  cards:        { title: "Card", desc: "Surface containers: outline, elevated, and inset variants." },
  toggles:      { title: "Checkbox & Switch", desc: "Two similar controls with different semantics." },
  table:        { title: "Table", desc: "Dense rows with hairline separators and subtle hover." },
  tabs:         { title: "Tabs", desc: "Underline tabs for pages, segmented tabs for inline toggles." },
  alerts:       { title: "Alert & Toast", desc: "Inline alerts and transient toasts, both monotone." },
  avatars:      { title: "Avatar", desc: "Initials on a neutral background. Three sizes, stackable." },
  accordion:    { title: "Accordion", desc: "Disclosure panels. Keyboard and screen reader behavior from Radix." },
  slider:       { title: "Slider", desc: "A range input for continuous values like volume or opacity." },
  toggle:       { title: "Toggle group", desc: "A segmented control for mutually-exclusive options." },
  kbd:          { title: "Kbd", desc: "Keyboard shortcut chips for menus and tooltips." },
  spinner:      { title: "Spinner", desc: "A monotone loading indicator for waits over 400ms." },
  textarea:     { title: "Textarea", desc: "Multi-line text input with Field wrapper support." },
  select:       { title: "Select", desc: "A dropdown for picking one option from a list. Wraps Radix UI Select." },
  layout:       { title: "Layout", desc: "Stack, Inline, Grid, and Container primitives for spacing and structure." },
  sheet:        { title: "Sheet", desc: "A slide-over panel from any edge. Built on Radix Dialog." },
  command:      { title: "Command palette", desc: "A searchable command menu with keyboard navigation. Opens on Cmd+K." },
  appshell:     { title: "AppShell", desc: "A composable application shell. Sidebar, header, content, and a mobile drawer baked in." },
  combobox:     { title: "Combobox", desc: "A searchable select for picking one option from a long list." },
  hovercard:    { title: "HoverCard", desc: "A rich tooltip shown on hover. For previewing what's behind a link or mention." },
  dialog:       { title: "Dialog", desc: "A modal that interrupts the user. Confirmations, simple forms, alerts." },
  tooltip:      { title: "Tooltip", desc: "A short label shown on hover or focus. Two or three words, max." },
  popover:      { title: "Popover", desc: "A floating panel anchored to a trigger. Inline forms, filter controls, color pickers." },
  dropdown:     { title: "Dropdown menu", desc: "A vertical list of actions triggered by a button." },
  radio:        { title: "Radio group", desc: "Pick one from a few. Use Select for longer lists." },
  skeleton:     { title: "Skeleton", desc: "A placeholder shape while real content loads." },
  empty:        { title: "Empty state", desc: "A friendly message and CTA when there's nothing to show." },
  paging:       { title: "Pagination", desc: "Page-by-page navigation for tables and long lists." },
  breadcrumb:   { title: "Breadcrumb", desc: "Show where the current page sits in the hierarchy." },
  progress:     { title: "Progress", desc: "A bar that fills as a measurable task makes progress." },
  separator:    { title: "Separator", desc: "A horizontal or vertical hairline. Use sparingly." },
  cli:          { title: "CLI", desc: "Add Monoset components to your project as source files with the monoset CLI." },
  llm:          { title: "LLM naming prompt", desc: "A prompt for adding stable data-ms attributes across a React codebase." },
  playground:   { title: "Playground", desc: "Try Monoset components live. Adjust props, preview the result, copy the code." },
  theming:      { title: "Theming Monoset", desc: "Dark mode, accent colors, and scoped themes." },
  settings:     { title: "Building a settings page", desc: "A real-world pattern composing Tabs, Cards, and form controls." },
  a11y:         { title: "Accessibility checklist", desc: "What Monoset handles, what you handle, and how to test." },
  nextjs:       { title: "Using with Next.js", desc: "App Router, Pages Router, and Server Component setup." },
  mcp:          { title: "MCP server", desc: "Give your AI coding agent direct access to Monoset components, tokens, and docs." },
  dashboard:    { title: "Building a dashboard", desc: "Sidebar, stat cards, and a data table in one layout." },
  datatable:    { title: "Data table with filters", desc: "Searchable, sortable, filterable table with row selection and bulk actions." },
};
