export const PAGE_META = {
  introduction: { title: "Introduction", desc: "What Monoset is, what ships in the box, and when to reach for it." },
  installation: { title: "Installation", desc: "Install Monoset via the CSS tokens or the React component kit." },
  usage:        { title: "Basic usage", desc: "An end-to-end example with Monoset tokens and primitives." },
  colors:       { title: "Colors", desc: "The 12-step neutral ramp and the semantic tokens built on top of it." },
  typography:   { title: "Typography", desc: "Inter for UI, JetBrains Mono for code, a modular scale from 11px to 64px." },
  spacing:      { title: "Spacing & radii", desc: "A 4px base grid with named spacing and radius tokens." },
  motion:       { title: "Motion", desc: "Three durations, one easing curve. Monoset's approach to UI motion." },
  framer:       { title: "Framer Motion", desc: "JS-driven animation presets that match the CSS motion tokens." },
  buttons:      { title: "Button", desc: "Four variants, three sizes, four states. A React Button component." },
  inputs:       { title: "Input", desc: "Text fields, textareas, and selects with a Field wrapper." },
  badges:       { title: "Badge", desc: "Small labels for status, counts, and category tags." },
  cards:        { title: "Card", desc: "Surface containers: outline, elevated, and inset variants." },
  toggles:      { title: "Checkbox & Switch", desc: "Two similar controls with different semantics." },
  table:        { title: "Table", desc: "Dense rows with hairline separators and subtle hover." },
  tabs:         { title: "Tabs", desc: "Underline tabs for pages, segmented tabs for inline toggles." },
  alerts:       { title: "Alert & Toast", desc: "Inline alerts and transient toasts, both monotone." },
  avatars:      { title: "Avatar", desc: "Initials on a neutral background. Three sizes, stackable." },
  accordion:    { title: "Accordion", desc: "Disclosure panels. Keyboard and screen reader behavior from Radix." },
  slider:       { title: "Slider", desc: "A range input for continuous values like volume or opacity." },
  toggle:       { title: "Toggle group", desc: "A segmented control for mutually-exclusive options." },
  kbd:          { title: "Kbd", desc: "Keyboard shortcut chips for menus and tooltips." },
  spinner:      { title: "Spinner", desc: "A monotone loading indicator for waits over 400ms." },
  llm:          { title: "LLM naming prompt", desc: "A prompt for adding stable data-ms attributes across a React codebase." },
};
