export const REACT_DOC_ROUTES = {
  introduction: "./groups/introduction.jsx",
  installation: "./groups/installation.jsx",
  usage: "./groups/usage.jsx",

  colors: "./groups/colors.jsx",
  typography: "./groups/typography.jsx",
  spacing: "./groups/spacing.jsx",
  motion: "./groups/motion.jsx",

  buttons: "./groups/buttons.jsx",
  inputs: "./groups/inputs.jsx",
  select: "./groups/select.jsx",
  toggles: "./groups/toggles.jsx",
  radio: "./groups/radio.jsx",

  combobox: "./groups/combobox.jsx",
  multicombobox: "./groups/multicombobox.jsx",
  datepicker: "./groups/datepicker.jsx",
  calendar: "./groups/calendar.jsx",
  numberinput: "./groups/numberinput.jsx",
  pininput: "./groups/pininput.jsx",
  password: "./groups/password.jsx",
  fileupload: "./groups/fileupload.jsx",
  slider: "./groups/slider.jsx",
  toggle: "./groups/toggle.jsx",

  badges: "./groups/badges.jsx",
  cards: "./groups/cards.jsx",
  avatars: "./groups/avatars.jsx",
  table: "./groups/table.jsx",
  alerts: "./groups/alerts.jsx",
  kbd: "./groups/kbd.jsx",
  spinner: "./groups/spinner.jsx",

  skeleton: "./groups/skeleton.jsx",
  empty: "./groups/empty.jsx",
  progress: "./groups/progress.jsx",
  accordion: "./groups/accordion.jsx",
  collapsible: "./groups/collapsible.jsx",
  carousel: "./groups/carousel.jsx",

  dialog: "./groups/dialog.jsx",
  sheet: "./groups/sheet.jsx",
  popover: "./groups/popover.jsx",
  tooltip: "./groups/tooltip.jsx",
  hovercard: "./groups/hovercard.jsx",
  dropdown: "./groups/dropdown.jsx",
  contextmenu: "./groups/contextmenu.jsx",
  command: "./groups/command.jsx",

  tabs: "./groups/tabs.jsx",
  navmenu: "./groups/navmenu.jsx",
  breadcrumb: "./groups/breadcrumb.jsx",
  paging: "./groups/paging.jsx",
  stepper: "./groups/stepper.jsx",

  layout: "./groups/layout.jsx",
  appshell: "./groups/appshell.jsx",
  separator: "./groups/separator.jsx",
  aspectratio: "./groups/aspectratio.jsx",

  cli: "./groups/cli.jsx",
  playground: "./groups/playground.jsx",
  llm: "./groups/llm.jsx",

  theming: "./groups/theming.jsx",
  a11y: "./groups/a11y.jsx",
  mcp: "./groups/mcp.jsx",
  nextjs: "./groups/nextjs.jsx",

  settings: "./groups/settings.jsx",
  dashboard: "./groups/dashboard.jsx",
  datatable: "./groups/datatable.jsx",
};

export const REACT_DOC_DEMOS = {
  "calendar-basic": { route: "calendar", module: "./demos/calendar.jsx" },
  "combobox-basic": { route: "combobox", module: "./demos/combobox.jsx" },
  "datepicker-basic": { route: "datepicker", module: "./demos/datepicker.jsx" },
  "multicombobox-basic": { route: "multicombobox", module: "./demos/multicombobox.jsx" },
  "numberinput-basic": { route: "numberinput", module: "./demos/numberinput.jsx" },
  "playground-button": { route: "playground", module: "./demos/playground/button.jsx" },
  "playground-badge": { route: "playground", module: "./demos/playground/badge.jsx" },
  "playground-alert": { route: "playground", module: "./demos/playground/alert.jsx" },
  "playground-avatar": { route: "playground", module: "./demos/playground/avatar.jsx" },
  "playground-card": { route: "playground", module: "./demos/playground/card.jsx" },
  "playground-input": { route: "playground", module: "./demos/playground/input.jsx" },
  "playground-textarea": { route: "playground", module: "./demos/playground/textarea.jsx" },
  "playground-switch": { route: "playground", module: "./demos/playground/switch.jsx" },
  "playground-checkbox": { route: "playground", module: "./demos/playground/checkbox.jsx" },
  "playground-spinner": { route: "playground", module: "./demos/playground/spinner.jsx" },
};
