import { describe, expect, it } from "vitest";
import packageJson from "../../package.json";
import * as root from "../index";
import * as toastModule from "../Toast";

const expectedRootExports = [
  "Accordion",
  "AccordionContent",
  "AccordionItem",
  "AccordionTrigger",
  "Alert",
  "AppShell",
  "AspectRatio",
  "Avatar",
  "Badge",
  "Breadcrumb",
  "Button",
  "Calendar",
  "CalendarDate",
  "Card",
  "Carousel",
  "Checkbox",
  "Collapsible",
  "CollapsibleContent",
  "CollapsibleTrigger",
  "Combobox",
  "CommandPalette",
  "Container",
  "ContextMenu",
  "ContextMenuCheckboxItem",
  "ContextMenuContent",
  "ContextMenuGroup",
  "ContextMenuItem",
  "ContextMenuItemIndicator",
  "ContextMenuLabel",
  "ContextMenuRadioGroup",
  "ContextMenuRadioItem",
  "ContextMenuSeparator",
  "ContextMenuSub",
  "ContextMenuSubContent",
  "ContextMenuSubTrigger",
  "ContextMenuTrigger",
  "DatePicker",
  "Dialog",
  "DialogClose",
  "DialogContent",
  "DialogTrigger",
  "DropdownMenu",
  "DropdownMenuCheckboxItem",
  "DropdownMenuContent",
  "DropdownMenuGroup",
  "DropdownMenuItem",
  "DropdownMenuItemIndicator",
  "DropdownMenuLabel",
  "DropdownMenuRadioGroup",
  "DropdownMenuRadioItem",
  "DropdownMenuSeparator",
  "DropdownMenuSub",
  "DropdownMenuSubContent",
  "DropdownMenuSubTrigger",
  "DropdownMenuTrigger",
  "EmptyState",
  "Field",
  "FileUpload",
  "Grid",
  "HoverCard",
  "HoverCardContent",
  "HoverCardTrigger",
  "Inline",
  "Input",
  "Kbd",
  "MonosetProvider",
  "MultiCombobox",
  "NavigationMenu",
  "NavigationMenuContent",
  "NavigationMenuIndicator",
  "NavigationMenuItem",
  "NavigationMenuLink",
  "NavigationMenuList",
  "NavigationMenuTrigger",
  "NavigationMenuViewport",
  "NumberInput",
  "Pagination",
  "PasswordInput",
  "PinInput",
  "Popover",
  "PopoverClose",
  "PopoverContent",
  "PopoverTrigger",
  "Progress",
  "Radio",
  "RadioGroup",
  "Select",
  "SelectContent",
  "SelectItem",
  "SelectTrigger",
  "Separator",
  "Sheet",
  "SheetClose",
  "SheetContent",
  "SheetTrigger",
  "Skeleton",
  "Slider",
  "Spinner",
  "Stack",
  "Stepper",
  "Switch",
  "Table",
  "TableHeader",
  "TableSelectAll",
  "TableSelectRow",
  "Tabs",
  "TabsContent",
  "TabsList",
  "TabsTrigger",
  "Textarea",
  "ThemeProvider",
  "ThemeToggle",
  "Toast",
  "ToastProvider",
  "Toggle",
  "ToggleGroup",
  "ToggleGroupItem",
  "Tooltip",
  "TooltipProvider",
  "cx",
  "calendarDateFromNativeDate",
  "calendarDateToNativeDate",
  "useAppShellMobile",
  "useTheme",
  "useToast",
].sort();

const expectedMotionExports = [
  "DUR",
  "EASE_EMPHASIS",
  "EASE_EXIT",
  "EASE_STANDARD",
  "Reveal",
  "fadeUp",
  "hoverLift",
  "listStagger",
  "modalPanel",
  "modalScrim",
  "popoverIn",
  "pressDown",
  "scaleIn",
  "slideInBottom",
  "slideInLeft",
  "slideInRight",
  "slideInTop",
].sort();

describe("React v1 exports", () => {
  it("publishes the exact root API", () => {
    expect(Object.keys(root).sort()).toEqual(expectedRootExports);
  });

  it("keeps Toast composition on the opinionated API", () => {
    expect(Object.keys(toastModule).sort()).toEqual([
      "Toast",
      "ToastProvider",
      "useToast",
    ]);
  });

  it("declares the built motion subpath", () => {
    expect(packageJson.exports["./motion" as keyof typeof packageJson.exports]).toEqual({
      import: {
        types: "./dist/motion.d.ts",
        default: "./dist/motion.js",
      },
      require: {
        types: "./dist/motion.d.cts",
        default: "./dist/motion.cjs",
      },
    });
  });

  it("publishes the exact motion API", async () => {
    const motionEntry = "../motion-entry";
    const motion = await import(/* @vite-ignore */ motionEntry).catch(() => ({}));

    expect(Object.keys(motion).sort()).toEqual(expectedMotionExports);
  });
});
